# Generated by Django 5.2.1 on 2025-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userauth_id_alter_userauth_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_log', models.JSONField()),
            ],
        ),
    ]
