# Generated by Django 5.2.1 on 2025-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSlip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_slip', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vacation', models.JSONField()),
            ],
        ),
    ]
