# Generated by Django 5.2.1 on 2025-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leaveslip_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveslip',
            name='leave_slip',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='vacation',
        ),
        migrations.AddField(
            model_name='leaveslip',
            name='future_slip',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='leaveslip',
            name='past_slip',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vacation',
            name='future_vacation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vacation',
            name='past_vacation',
            field=models.JSONField(default=list),
        ),
    ]
