# Generated by Django 5.2.1 on 2025-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_leaveslip_leave_slip_remove_vacation_vacation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveslip',
            name='future_slip',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='leaveslip',
            name='past_slip',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='future_vacation',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='past_vacation',
            field=models.JSONField(),
        ),
    ]
