# Generated by Django 5.2.1 on 2025-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_leaveslip_future_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveslip',
            name='remaining_time',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='vacation',
            name='remaining_vacation',
            field=models.IntegerField(default=14),
        ),
    ]
