# Generated by Django 5.2.1 on 2025-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_leaveslip_remaining_time_vacation_remaining_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('remaining_time', models.IntegerField(max_length=100)),
            ],
        ),
    ]
