# Generated by Django 5.2.1 on 2025-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_timerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerdata',
            name='timer_type',
            field=models.CharField(default='OFF', max_length=4),
        ),
    ]
