# Generated by Django 5.2.1 on 2025-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_timerdata_timer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerdata',
            name='remaining_time',
            field=models.IntegerField(),
        ),
    ]
