# Generated by Django 5.2.1 on 2025-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_timerdata_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
