# Generated by Django 5.2.1 on 2025-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_timerdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
