# Generated by Django 5.2.1 on 2025-08-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userdata_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveslip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userauth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userauth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userauth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userauth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userauth'),
            preserve_default=False,
        ),
    ]
