name: Build and deploy Python app to Azure Web App - petruzdroba

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd techtreck-learning/backend
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd techtreck-learning/backend
          zip -r ../../release.zip ./*

      - name: List files in root after zipping
        run: ls -l

      - name: List files in release.zip
        run: unzip -l release.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBD1E53FEC764480BB9EE70A22DB9F85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E9FAC95E9774DFB94BC5DEC0B2A52AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF0A2C78B1EB4363ABA5457466F8BAD2 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "petruzdroba"
          slot-name: "Production"
          package: release.zip
          type : zip
